"""create games game_players game_events tables

Revision ID: faa1a0411c89
Revises: b689030b915e
Create Date: 2026-05-12 10:18:58.288903

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "faa1a0411c89"
down_revision: str | Sequence[str] | None = "b689030b915e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("room_code", sa.String(), nullable=True),
        sa.Column("ruleset", sa.String(), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("ended_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("round_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("ts", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "seq", name="uq_game_events_seq"),
    )
    op.create_index(
        op.f("ix_game_events_game_id"), "game_events", ["game_id"], unique=False
    )
    op.create_table(
        "game_players",
        sa.Column("game_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("seat_idx", sa.Integer(), nullable=False),
        sa.Column("final_score", sa.Integer(), nullable=True),
        sa.Column("fouled_rounds", sa.Integer(), nullable=False),
        sa.Column("fantasy_rounds", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("game_id", "user_id"),
    )
    op.create_index(
        op.f("ix_game_players_user_id"), "game_players", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_players_user_id"), table_name="game_players")
    op.drop_table("game_players")
    op.drop_index(op.f("ix_game_events_game_id"), table_name="game_events")
    op.drop_table("game_events")
    op.drop_table("games")
    # ### end Alembic commands ###
